<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AutopilotQuant.Core\AutopilotQuant.Core.csproj" />
    <PackageReference Include="Google.Protobuf" Version="3.36.1" />
    <PackageReference Include="Grpc.Tools" Version="2.84.0" PrivateAssets="All" />
    <Protobuf Include="Protocol\configuration.proto" GrpcServices="None" />
  </ItemGroup>
</Project>
